# This is a basic workflow to help you get started with Actions

name: build and release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build apk
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Flutter action
      uses: subosito/flutter-action@v1.3.2
      with:
        flutter-version: '1.17.3'
    - run: flutter pub get
    - run: flutter build apk --release --split-per-abi
    - run: flutter build appbundle
    - run: flutter build apk
    - name: Upload app bundle
      uses: actions/upload-artifact@v2
      with:
        name: appbundle
        path: build/app/outputs/bundle/release/app-release.aab
    - name: Upload app apk
      uses: actions/upload-artifact@v2
      with:
        name: app apk
        path: build/app/outputs/apk/release/app-release.apk
    - name: Create app bundle Release
      uses: actions/create-release@v1.1.1
      with:
        artifacts: "build/app/outputs/bundle/release/app-release.aab"
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        token: ${{ secrets.TOKEN }}
        commit: ${{github.sha}}
    - name: Create app apk Release
      uses: actions/create-release@v1.1.1
      with:
        artifacts: "build/app/outputs/apk/release/app-release.apk"
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        token: ${{ secrets.TOKEN }}
        commit: ${{github.sha}}
  
